@startuml
title C4 – Cercare Libro

actor Utente
participant "Schermata di Ricerca Libri" as SRL
participant ":GestoreLibri" as GL

Utente -> SRL : inserisciCriteriBase(titolo, autore, ISBN)
SRL -> GL : cercaLibro(criteriBase)
activate GL

alt Flusso alternativo (criteri avanzati)
    Utente -> SRL : inserisciCriteriAvanzati(disponibilita, anno)
    SRL -> GL : cercaLibro(criteriAvanzati)
    GL --> SRL : listaRisultati : List<Libro>

else Flusso normale (ricerca base)
    GL --> SRL : listaRisultati : List<Libro>
end

deactivate GL

SRL --> Utente : visualizzaRisultati(listaRisultati)

@enduml
