@startuml
title C6 – Inserire Utente

actor Utente
participant "Schermata Gestione Utenti" as SGU
participant ":GestoreUtenti" as GU
participant "Utente_Entità" as UE

Utente -> SGU : cliccaAggiungiUtente()
Utente -> SGU : inserisciDati(nome, cognome,\nmatricola, contatti)

alt Salvataggio dati (Flusso normale)
    Utente -> SGU : cliccaSalva()
    SGU -> GU : aggiungi(dati)
    activate GU

    GU -> UE : create(dati)
    activate UE
    deactivate UE

    GU --> SGU : OK / Utente aggiunto
    deactivate GU

    SGU --> Utente : mostraConferma()

else Annullamento operazione (Flusso alternativo)
    Utente -> SGU : cliccaAnnulla()
    SGU --> Utente : tornaAVisualizzazioneUtenti()
end

@enduml
